// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MVVMC.iOS.Scenes.Splash
{
	public partial class SplashViewController : UIViewController
	{
		public SplashViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
